[workspace]
resolver = "3"
members = [
    "crates/pam-native-cli",
    "crates/pam-native-engine",
    "crates/pam-native-protocol",
]
exclude = ["pam-cli"]

[workspace.package]
version = "1.0.11"
edition = "2024"
rust-version = "1.88"
license = "Apache-2.0"
repository = "https://github.com/push-in/pam-native"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
overflow-checks = false
panic = "abort"
strip = "symbols"

[profile.performance]
inherits = "release"
debug = "line-tables-only"
strip = "none"
