[workspace]
resolver = "3"
members = [
    "crates/pam-native-engine",
    "crates/pam-native-protocol",
]

[workspace.package]
version = "0.6.62"
edition = "2024"
rust-version = "1.88"
license = "Apache-2.0"
repository = "https://github.com/push-in/pam-native"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "thin"
overflow-checks = false
panic = "abort"
strip = "symbols"
