<?php

declare(strict_types=1);

namespace Pam\Native\Internal;

use RuntimeException;
use Throwable;

/**
 * Collects the expression sources a compiled template can evaluate and
 * writes them as one PHP file of generated closures, so components load
 * their expressions with the compiled class instead of parsing them at
 * render time.
 *
 * @internal
 */
final class TemplateExpressionCatalog
{
    private const DIRECTIVES = ['p-if', 'p-else-if', 'v-if', 'v-else-if', 'p-key'];

    private function __construct()
    {
    }

    /** @return list<string> */
    public static function collect(CompiledTemplateNode $tree): array
    {
        $expressions = [];
        self::visit($tree, $expressions);

        return array_map(strval(...), array_keys($expressions));
    }

    /**
     * PHP source returning the generated closures by expression; expressions
     * that do not compile are left to the runtime (which reports them).
     */
    public static function source(CompiledTemplateNode $tree): string
    {
        $entries = [];
        foreach (self::collect($tree) as $expression) {
            try {
                $closure = TemplateExpressionCompiler::closureSource($expression);
            } catch (RuntimeException) {
                continue;
            }
            $entries[] = '    '.var_export($expression, true).' => '.$closure.',';
        }

        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by PAM Native: compiled template expressions.\nreturn [\n"
            .implode("\n", $entries)."\n];\n";
    }

    /** Registers a generated expression file; a stale or broken file is ignored. */
    public static function load(string $file): void
    {
        if (!is_file($file)) {
            return;
        }
        try {
            $closures = require $file;
        } catch (Throwable) {
            return;
        }
        if (is_array($closures)) {
            TemplateExpression::preload(array_filter(
                $closures,
                static fn (mixed $closure, mixed $expression): bool =>
                    (is_string($expression) || is_int($expression)) && $closure instanceof \Closure,
                ARRAY_FILTER_USE_BOTH,
            ));
        }
    }

    /** @param array<string, true> $expressions */
    private static function visit(CompiledTemplateNode $node, array &$expressions): void
    {
        if ($node->kind === 2) {
            self::interpolations($node->value, $expressions);
        }
        foreach ($node->attributes as $name => $value) {
            if (!is_string($value) || $name === '__pamStyles') {
                continue;
            }
            if (str_starts_with($name, ':') || in_array($name, self::DIRECTIVES, true)) {
                $expressions[$value] = true;
                continue;
            }
            if ($name === 'p-for' || $name === 'v-for') {
                if (preg_match('/^\s*\$?([A-Za-z_][A-Za-z0-9_]*)\s+in\s+(.+)\s*$/D', $value, $match) === 1) {
                    $expressions[$match[2]] = true;
                }
                continue;
            }
            if (str_contains($value, '{{')) {
                self::interpolations($value, $expressions);
            } elseif (preg_match('/^[A-Za-z_][A-Za-z0-9_]*\s*\(/D', $value) === 1) {
                $expressions[$value] = true;
            }
        }
        foreach ($node->children as $child) {
            self::visit($child, $expressions);
        }
    }

    /** @param array<string, true> $expressions */
    private static function interpolations(string $value, array &$expressions): void
    {
        if (
            str_contains($value, '{{')
            && preg_match_all('/\{\{\s*(.*?)\s*\}\}/s', $value, $matches) > 0
        ) {
            foreach ($matches[1] as $expression) {
                $expressions[$expression] = true;
            }
        }
    }
}
