<?php

declare(strict_types=1);

namespace Pam\Native\Internal;

use RuntimeException;
use Throwable;

use function in_array;
use function is_array;
use function is_string;
use function strlen;
use function strval;

/**
 * Collects the expression sources a compiled template can evaluate and
 * writes them as one PHP file of generated closures, so components load
 * their expressions with the compiled class instead of parsing them at
 * render time.
 *
 * @internal
 */
final class TemplateExpressionCatalog
{
    private const DIRECTIVES = ['p-if', 'p-else-if', 'v-if', 'v-else-if', 'p-key'];

    /** Key prefix of compiled `:class` lists in generated files. */
    public const CLASS_LIST_PREFIX = "\0class\0";

    /** Key of the template JSON in a bundle template file (see bundleSource()). */
    public const TEMPLATE_KEY = "\0template";

    private function __construct()
    {
    }

    /** @return list<string> */
    public static function collect(CompiledTemplateNode $tree): array
    {
        $expressions = [];
        self::visit($tree, $expressions);

        return array_map(strval(...), array_keys($expressions));
    }

    /**
     * PHP source returning the generated closures by expression; expressions
     * that do not compile are left to the runtime (which reports them).
     */
    public static function source(CompiledTemplateNode $tree): string
    {
        return self::generate($tree, []);
    }

    /**
     * One bundle file per prebuilt component: the generated closures plus the
     * runtime template JSON under TEMPLATE_KEY (one file to install and one
     * opcode-cached include instead of a closure file and a JSON file).
     */
    public static function bundleSource(CompiledTemplateNode $tree, string $templateJson): string
    {
        $entry = '    '.var_export(self::TEMPLATE_KEY, true).' => '.var_export($templateJson, true).',';
        try {
            return self::generate($tree, [$entry]);
        } catch (RuntimeException) {
            // Expressions still compile on first use; the template must ship.
            return "<?php\n\ndeclare(strict_types=1);\n\nreturn [\n".$entry."\n];\n";
        }
    }

    /** @param list<string> $entries */
    private static function generate(CompiledTemplateNode $tree, array $entries): string
    {
        foreach (self::collect($tree) as $expression) {
            try {
                $closure = TemplateExpressionCompiler::closureSource($expression);
            } catch (RuntimeException) {
                continue;
            }
            $entries[] = '    '.var_export($expression, true).' => '.$closure.',';
        }
        foreach (self::classLists($tree) as $expression) {
            $closure = TemplateExpressionCompiler::classListSource($expression);
            if ($closure !== null) {
                $entries[] = '    '.var_export(self::CLASS_LIST_PREFIX.$expression, true).' => '.$closure.',';
            }
        }

        // A short alias keeps generated files small (bundle size, opcode cache).
        $body = str_replace('\\'.TemplateExpression::class.'::', 'E::', implode("\n", $entries));

        return "<?php\n\ndeclare(strict_types=1);\n\nuse ".TemplateExpression::class." as E;\n\n"
            ."// Generated by PAM Native: compiled template expressions.\nreturn [\n".$body."\n];\n";
    }

    /** Registers a generated expression file; a stale or broken file is ignored. */
    public static function load(string $file): void
    {
        if (!is_file($file)) {
            return;
        }
        try {
            $closures = require $file;
        } catch (Throwable) {
            return;
        }
        if (is_array($closures)) {
            self::register($closures);
        }
    }

    /**
     * Registers the closures of a bundleSource() file and returns its
     * template JSON (null when the file is missing or broken).
     */
    public static function loadBundle(string $file): ?string
    {
        try {
            $entries = require $file;
        } catch (Throwable) {
            return null;
        }
        if (!is_array($entries) || !is_string($entries[self::TEMPLATE_KEY] ?? null)) {
            return null;
        }
        self::register($entries);

        return $entries[self::TEMPLATE_KEY];
    }

    /** @param array<array-key, mixed> $closures */
    private static function register(array $closures): void
    {
        $expressions = [];
        $classLists = [];
        foreach ($closures as $expression => $closure) {
            if (!$closure instanceof \Closure) {
                continue;
            }
            $expression = (string) $expression;
            if (str_starts_with($expression, self::CLASS_LIST_PREFIX)) {
                $classLists[substr($expression, strlen(self::CLASS_LIST_PREFIX))] = $closure;
            } else {
                $expressions[$expression] = $closure;
            }
        }
        TemplateExpression::preload($expressions, $classLists);
    }

    /** @return list<string> `:class` expressions of the template */
    private static function classLists(CompiledTemplateNode $node): array
    {
        $lists = [];
        $value = $node->attributes[':class'] ?? null;
        if (is_string($value)) {
            $lists[] = $value;
        }
        foreach ($node->children as $child) {
            array_push($lists, ...self::classLists($child));
        }

        return array_values(array_unique($lists));
    }

    /** @param array<string, true> $expressions */
    private static function visit(CompiledTemplateNode $node, array &$expressions): void
    {
        if ($node->kind === 2) {
            self::interpolations($node->value, $expressions);
        }
        foreach ($node->attributes as $name => $value) {
            if (!is_string($value) || $name === '__pamStyles') {
                continue;
            }
            if (str_starts_with($name, ':') || in_array($name, self::DIRECTIVES, true)) {
                $expressions[$value] = true;
                continue;
            }
            if ($name === 'p-for' || $name === 'v-for') {
                if (preg_match('/^\s*\$?([A-Za-z_][A-Za-z0-9_]*)\s+in\s+(.+)\s*$/D', $value, $match) === 1) {
                    $expressions[$match[2]] = true;
                }
                continue;
            }
            if (str_contains($value, '{{')) {
                self::interpolations($value, $expressions);
            } elseif (preg_match('/^[A-Za-z_][A-Za-z0-9_]*\s*\(/D', $value) === 1) {
                $expressions[$value] = true;
            }
        }
        foreach ($node->children as $child) {
            self::visit($child, $expressions);
        }
    }

    /** @param array<string, true> $expressions */
    private static function interpolations(string $value, array &$expressions): void
    {
        if (
            str_contains($value, '{{')
            && preg_match_all('/\{\{\s*(.*?)\s*\}\}/s', $value, $matches) > 0
        ) {
            foreach ($matches[1] as $expression) {
                $expressions[$expression] = true;
            }
        }
    }
}
